### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Nikitaenterprise** [Nikitaenterprise/Excel#3]
- [ ] Make a GUI
- [x] Make an executable file with pyinstaller
    - [ ] Make automatic creation of executable
- [ ] Make custom exceptions class
- [ ] Make a log system
